[package]
name = "go"
version = "0.1.0"
edition = "2021"
resolver = "2"

[package.metadata]
chip = "ATSAMD21G18A"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7", optional = true }

atsamd-hal = { version = "0.23.3", default-features = false}

usb-device = { version ="0.3.2", optional = true }
usbd-serial ={ version = "0.2.2", optional = true }

libm = "0.2.16"
defmt = "1.1.0"
portable-atomic = "1.13.1"

embassy-time = { version = "0.5.1", features = ["defmt", "tick-hz-1_000"] }
embassy-time-driver = "0.2.2"
embassy-executor = { version = "0.10.0", features = ["defmt", "executor-thread", "platform-cortex-m"] }

bmp390-rs = { version = "0.4.0", features = ["uom"] }
uom = { version = "0.37.0", features = ["f32", "si"], default-features = false }

critical-section = "1.2.0"
bmi323-rs = { path = "bmi323-rs", features = ["defmt"] }
micromath = { version = "2.1.0", features = ["vector"] }
embassy-embedded-hal = "0.6.0"
embassy-sync = "0.8.0"
static_cell = { version = "2.1.0" }
embedded-sdmmc = { version = "0.9.0", default-features = false }
embedded-hal-bus = { version = "0.3.0", features = ["async", "defmt-03"] }

[features]
default = ["rt", "usb", "async", "dma", "atsamd-hal/samd21g"]
rt = ["dep:cortex-m-rt", "atsamd-hal/samd21g-rt"]
usb = ["atsamd-hal/usb", "dep:usb-device", "dep:usbd-serial",]
async = ["atsamd-hal/async"]
dma = ["atsamd-hal/dma"]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
debug = true
